-- create ETL sechma
CREATE SCHEMA ETL;

-- create VIDEOSTART_RAW to load the raw file
CREATE TABLE ETL.VIDEOSTART_RAW
(
	DATETIME VARCHAR(30),
    VIDEOTITLE VARCHAR(200),
    EVENTS VARCHAR(150)
);

-- create VIDEOSTART_DLT to store the data after data transfermation
CREATE TABLE ETL.VIDEOSTART_DLT 
(
	DATETIME TIMESTAMP NOT NULL, 
	PLATFORM VARCHAR(200) NOT NULL, 
	SITE  VARCHAR(200) NOT NULL, 
	VIDEO VARCHAR(200) NOT NULL
);

-- create DIMDATE_DLT to store DATETIME data from raw file
--DATETIME IS DEFINED AS VARCHAR(12) IN THE FORMAT OF '%Y%m%d%H%i' like '202001011521' to minutes grain as required;
CREATE TABLE ETL.DIMDATE_DLT
(
	DATETIME VARCHAR(12) NOT NULL,
    CONSTRAINT DIMDATE_DLT_PK PRIMARY KEY(DATETIME)
);

-- create DIMPLATFORM_DLT to store PLATFORM data from raw file
CREATE TABLE ETL.DIMPLATFORM_DLT
(
	PLATFORM VARCHAR(200) NOT NULL,
    CONSTRAINT DIMPLATFORM_PK PRIMARY KEY(PLATFORM)
);

-- create DIMSITE_DLT to store SITE data from raw file
CREATE TABLE ETL.DIMSITE_DLT
(
	SITE VARCHAR(200) NOT NULL,
    CONSTRAINT DIMSITE_DLT_PK PRIMARY KEY (SITE)
);

-- create DIMVIDEO_DLT to store VIDEO data from raw file
CREATE TABLE ETL.DIMVIDEO_DLT
(
	VIDEO VARCHAR(200) NOT NULL,
    CONSTRAINT DIMVIDEO_DLT_PK PRIMARY KEY (VIDEO)
);

-- create dimension table DIMDATE
CREATE TABLE ETL.DIMDATE
(
	DATETIME_SKEY VARCHAR(12) NOT NULL,
    CONSTRAINT DIMDATE_PK PRIMARY KEY (DATETIME_SKEY)
);

-- create dimension table DIMPLATFORM
CREATE TABLE ETL.DIMPLATFORM
(
	PLATFORM_SKEY INT NOT NULL AUTO_INCREMENT,
    PLATFORM VARCHAR(200) NOT NULL,
	PRIMARY KEY (PLATFORM_SKEY)
);

--INITIALLY INSERT ONE RECORD
INSERT INTO ETL.DIMPLATFORM VALUES(0, 'Unknow');
-- create dimension table DIMSITE
CREATE TABLE ETL.DIMSITE
(
	SITE_SKEY INT NOT NULL AUTO_INCREMENT,
    SITE VARCHAR(200) NOT NULL,
    CONSTRAINT DIMSITE_PK PRIMARY KEY (SITE_SKEY)
);

--INITIALLY INSERT ONE RECORD
INSERT INTO ETL.DIMSITE VALUES(0, 'Unknow');
-- create dimension table DIMVIDEO
CREATE TABLE ETL.DIMVIDEO
(
	VIDEO_SKEY INT NOT NULL AUTO_INCREMENT,
    VIDEO VARCHAR(200) NOT NULL,
    CONSTRAINT DIMVIDEO_PK PRIMARY KEY (VIDEO_SKEY)
);

--INITIALY INSERT ONE RECORD
INSERT INTO ETL.DIMVIDEO VALUES(0, 'Unknow');

-- create FACTVIDEOSTART to store the transaction data
CREATE TABLE ETL.FACTVIDEOSTART
(
	DATETIME_SKEY VARCHAR(12) NOT NULL,
    PLATFORM_SKEY INT NOT NULL,
    SITE_SKEY INT NOT NULL,
    VIDEO_SKEY INT NOT NULL,
    SYSTIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);