CREATE SCHEMA ETL;

CREATE TABLE ETL.VIDEOSTART_RAW
(
	DATETIME VARCHAR(30),
    VIDEOTITLE VARCHAR(200),
    EVENTS VARCHAR(150)
);


CREATE TABLE ETL.VIDEOSTART_DLT 
(
	DATETIME TIMESTAMP (6) NOT NULL, 
	PLATFORM VARCHAR(200) NOT NULL, 
	SITE  VARCHAR(200) NOT NULL, 
	VIDEO VARCHAR(200) NOT NULL
);

CREATE TABLE ETL.DIMDATE_DLT
(
	DATETIME TIMESTAMP(6) NOT NULL,
    CONSTRAINT DIMDATE_DLT_PK PRIMARY KEY(DATETIME)
);

CREATE TABLE ETL.DIMPLATFORM_DLT
(
	PLATFORM VARCHAR(200) NOT NULL,
    CONSTRAINT DIMPLATFORM_PK PRIMARY KEY(PLATFORM)
);

CREATE TABLE ETL.DIMSITE_DLT
(
	SITE VARCHAR(200) NOT NULL,
    CONSTRAINT DIMSITE_DLT_PK PRIMARY KEY (SITE)
);

CREATE TABLE ETL.DIMVIDEO_DLT
(
	VIDEO VARCHAR(200) NOT NULL,
    CONSTRAINT DIMVIDEO_DLT_PK PRIMARY KEY (VIDEO)
);

CREATE TABLE ETL.DIMDATE
(
	DATETIME_SKEY VARCHAR(12) NOT NULL,
    CONSTRAINT DIMDATE_PK PRIMARY KEY (DATETIME_SKEY)
);

CREATE TABLE ETL.DIMPLATFORM
(
	PLATFORM_SKEY INT NOT NULL AUTO_INCREMENT,
    VIDEO VARCHAR(200) NOT NULL,
	PRIMARY KEY (PLATFORM_SKEY)
);

--INITIALLY INSERT ONE RECORD
INSERT INTO ETL.DIMPLATFORM VALUES(0, 'Unknow');

CREATE TABLE ETL.DIMSITE
(
	SITE_SKEY INT NOT NULL AUTO_INCREMENT,
    SITE VARCHAR(200) NOT NULL,
    CONSTRAINT DIMSITE_PK PRIMARY KEY (SITE_SKEY)
);

--INITIALLY INSERT ONE RECORD
INSERT INTO ETL.DIMSITE VALUES(0, 'Unknow');

CREATE TABLE ETL.DIMVIDEO
(
	VIDEO_SKEY INT NOT NULL AUTO_INCREMENT,
    VIDEO VARCHAR(200) NOT NULL,
    CONSTRAINT DIMVIDEO_PK PRIMARY KEY (VIDEO_SKEY)
);

--INITIALY INSERT ONE RECORD
INSERT INTO ETL.DIMVIDEO VALUES(0, 'Unknow');

CREATE TABLE ETL.FACTVIDEOSTART
(
	DATETIME_SKEY VARCHAR(12) NOT NULL,
    PLATFORM_SKEY INT NOT NULL,
    SITE_SKEY INT NOT NULL,
    VIDEO_SKEY INT NOT NULL
);